### ISSUE TITLE
Replace `new static` with `new self` or finalize classes

### ISSUE THREAD

**Issue by tarampampam** [avtocod/b2b-api-php#12]
PHPStan errors:

```
 ------ ------------------------------------------------------- 
  103    Unsafe usage of new static().                          
         💡 Consider making the class or the constructor final.  
 ------ ------------------------------------------------------- 

 ------ ------------------------------------------------------- 
  Line   Responses/UserResponse.php                             
 ------ ------------------------------------------------------- 
  91     Unsafe usage of new static().                          
         💡 Consider making the class or the constructor final.  
 ------ ------------------------------------------------------- 
```

Now disabled:

```yaml
parameters:
  # ...
  ignoreErrors:
    - # Replacing with `return new self` or classes finalization requires major version upping. Make it on next major release
      message: '#Unsafe usage of new static\(\)#'
      paths:
        - src/Responses/*Response.php
        - src/Responses/Entities/*.php
        - src/Exceptions/*Exception.php
```

We must replace `new static` with `new self` or finalize classes in **new major version (v4.x)**
